# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOL' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SOL
  pod "SwiftUIRefresh"
  pod 'ToastUI'
  pod 'ISEmojiView'
  pod 'CalendarKit'
 
  target 'SOLTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SOLUITests' do
    # Pods for testing
  end

end
